feat: added custom time parsing (keptn/keptn#4788)
keptn/go-utils pull request #348
Opened 2021-11-08 07:50 UTC by RealAnna

## This PR

-  change time parsing to a custom one to avoid parsing errors
-  In the order we try :
      - ISO8601 :  000Z format
      -  then RFC3339 : "2019-10-12T07:20:50.52Z" 
      - finally a fallback userfriendly format : "2006-01-02T15:04:05"
     

### Related Issues
 #kept/keptn#4788 

##Notes
RFC 3339 is following the ISO 8601 DateTime format. The only difference is RFC allows us to replace “T” with “space”

2021-11-08 08:40 UTC, thisthat commented on pkg/common/timeutils/timeutils.go
> +
Please, remove this unused code

2021-11-08 08:40 UTC, thisthat commented on pkg/common/timeutils/timeutils.go
> +	var temp *time.Time
why this temp var?

2021-11-08 10:52 UTC, thisthat commented on pkg/common/timeutils/timeutils.go
> +//If this fails as well, an error is returned
```suggestion
// if this is not possible, the fallback format RFC3339  will be used, then '2006-01-02T15:04:05'.
// If this fails as well, an error is returned
```

2021-11-08 10:52 UTC, thisthat commented on pkg/common/timeutils/timeutils.go
> +	start = &calcStart
I think the previous code it is easier to read, but I would have it with some of your changes
```suggestion
	end := time.Now().UTC()
	start := end.Add(-timeframeDuration)
```

2021-11-08 12:24 UTC, warber requested changes

2021-11-08 12:24 UTC, warber commented on pkg/common/timeutils/timeutils.go
> +	//var timeFormat string
pls remove this line

2021-11-09 10:21 UTC, warber approved these changes

2021-11-09 10:21 UTC, merged